### ISSUE TITLE
可否直接生成单排横象格式

### ISSUE THREAD

**Issue by huilang-me** [pspgbhu/FrameSpriteMaker#1]
这样只要改变background-position-x就可以生成动画了

**Comment by pspgbhu** [comment]
目前是默认十个一排，可以考虑近期增加自定义每行个数的选项。

**Comment by pspgbhu** [comment]
嗯，在最新的代码中已经加入了自定义行数的选项了，当然也可以生成单行的雪碧图，欢迎使用。
没有什么问题的话，我就关闭这个issue了😊。

**Comment by huilang-me** [comment]
给力 谢谢
